import type { InitOptions, GeneratorOutput, CustomProviderDef } from '../types.js'

export async function generateCustom(provider: CustomProviderDef, options: InitOptions, _cwd: string): Promise<GeneratorOutput> {
  const files: GeneratorOutput['files'] = []

  let content = ''

  switch (provider.configFormat) {
    case 'json': {
      content = JSON.stringify({
        name: provider.name,
        description: provider.description,
        project: options.projectName,
        agents: options.agents.length,
        agentDepth: options.agentDepth,
        agentList: options.agents.map((a) => ({
          id: a.id,
          name: a.name,
          category: a.category,
          description: a.description,
          permissions: a.permissions || 'read-only',
        })),
        generatedBy: 'agents-profiles-cli',
      }, null, 2)
      break
    }
    case 'yaml':
    case 'toml': {
      const separator = provider.configFormat === 'yaml' ? ':' : ' ='
      content = `# ${provider.name} — ${options.projectName}
# Auto-generated by agents-profiles-cli
# ${provider.description}

project${separator} ${options.projectName}
agent_count${separator} ${options.agents.length}
agent_depth${separator} ${options.agentDepth}

agents${separator}
${options.agents.map((a) => `  - id${separator} ${a.id}
    name${separator} ${a.name}
    category${separator} ${a.category}
    description${separator} ${a.description}
    permissions${separator} ${a.permissions || 'read-only'}`).join('\n')}
`
      break
    }
    case 'markdown':
    default: {
      content = `# ${provider.name} — ${options.projectName}

> ${provider.description}

## Project
- **Name:** ${options.projectName}
- **Agents:** ${options.agents.length}
- **Depth:** ${options.agentDepth}

## Agents

${options.agents.map((a) => `### ${a.name} (\`${a.id}\`)
- **Category:** ${a.category}
- **Description:** ${a.description}
- **Permissions:** ${a.permissions || 'read-only'}`).join('\n\n')}

---
*Generated by agents-profiles-cli*
`
      break
    }
  }

  files.push({
    path: provider.configFilePath,
    content,
  })

  return { platform: provider.id, files, agentFiles: [] }
}
